[server]
headless = true
address = "127.0.0.1"
#port = 5000
port = 8501

[theme]
base = "dark"
primaryColor = "#64ffda"
backgroundColor = "#18191a"
secondaryBackgroundColor = "#212529"
textColor = "#e4e6eb"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[browser]
gatherUsageStats = false
